{% set version = "5.1.0" %}

package:
  name: asphalt-sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asphalt-sqlalchemy/asphalt-sqlalchemy-{{ version }}.tar.gz
  sha256: 7ddfdf9f772e1193d25a1fec245f519c54ab0635b5387c536f0b3b77bf9c1a66

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - asphalt >=4.9,<5
    - sqlalchemy >=2.0

test:
  imports:
    - asphalt.sqlalchemy

about:
  home: https://github.com/asphalt-framework/asphalt-sqlalchemy
  doc_url: https://asphalt-sqlalchemy.readthedocs.org
  dev_url: https://github.com/asphalt-framework/asphalt-sqlalchemy
  license: Apache-2.0
  license_file: LICENSE
  summary: SQLAlchemy integration component for the Asphalt framework

extra:
  recipe-maintainers:
    - davidbrochart
